'use client';

import React from 'react';

export default function TermsOfUse() {
  return (
    <div className="container legal-page">
      <div className="legal-header">
        <h1 className="font-mono text-brand">Terms of Use</h1>
        <p className="legal-updated">Effective Date: July 12, 2026 &nbsp;|&nbsp; Last Updated: July 12, 2026</p>
      </div>

      <div className="legal-content font-mono">

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the BondFactor fixed income analytics platform, including our website, application programming interfaces, and related services (collectively, the &quot;Platform&quot;), you agree to be bound by these Terms of Use (&quot;Terms&quot;). If you do not agree to these Terms, do not access or use the Platform.
          </p>
          <p>
            These Terms constitute a legally binding agreement between you and BondFactor (&quot;BondFactor,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
          </p>
        </section>

        <section>
          <h2>2. Definitions</h2>
          <ul>
            <li><strong>&quot;Service&quot;</strong> refers to the Platform, including all features, tools, analytics, calculations, models, APIs, documentation, and related services.</li>
            <li><strong>&quot;User,&quot; &quot;You,&quot;</strong> refers to any individual or entity that accesses or uses the Service.</li>
            <li><strong>&quot;Content&quot;</strong> refers to all data, text, outputs, analytics, yield curves, risk calculations, reports, and other material generated by or available through the Service.</li>
            <li><strong>&quot;User Content&quot;</strong> refers to data, portfolios, scenarios, and configurations that you input or upload to the Service.</li>
          </ul>
        </section>

        <section>
          <h2>3. Eligibility</h2>
          <p>
            The Service is intended for use by individuals who are at least 18 years of age and have the legal capacity to enter into binding agreements. By using the Service, you represent and warrant that you meet these requirements.
          </p>
        </section>

        <section>
          <h2>4. Account Registration and Security</h2>
          <p>
            Certain features of the Service require you to create an account. When registering, you agree to provide accurate, current, and complete information. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials.</li>
            <li>All activities that occur under your account.</li>
            <li>Notifying us immediately of any unauthorized use of your account or any other breach of security.</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate your account if we reasonably believe that the information you provided is inaccurate, incomplete, or outdated, or if you have violated these Terms.
          </p>
        </section>

        <section>
          <h2>5. Intellectual Property</h2>
          <p>
            The Service and all associated intellectual property, including but not limited to software, source code, algorithms, yield curve models, risk calculation methodologies, analytics engines, user interfaces, designs, logos, trademarks, and documentation, are the exclusive property of BondFactor and are protected by applicable intellectual property laws.
          </p>
          <p>
            Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your internal, non-commercial analytical and educational purposes.
          </p>
          <p>You shall not:</p>
          <ul>
            <li>Copy, modify, distribute, sell, or lease any part of the Service or its Content.</li>
            <li>Reverse engineer, decompile, or disassemble any software underlying the Service.</li>
            <li>Remove, alter, or obscure any proprietary notices or labels.</li>
            <li>Use the Service to develop a competing product or service.</li>
          </ul>
        </section>

        <section>
          <h2>6. Acceptable Use</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You shall not:</p>
          <ul>
            <li>Use the Service for any unlawful, fraudulent, or malicious purpose.</li>
            <li>Circumvent, disable, or interfere with security features or usage limits.</li>
            <li>Access the Service via automated means (bots, scrapers) without our prior written consent.</li>
            <li>Resell, sublicense, or redistribute the Service or its Content.</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
            <li>Upload malicious code or content that could harm the Service or other users.</li>
            <li>Share your account credentials with any third party.</li>
            <li>Use the Service to manipulate markets or engage in any form of insider trading or market abuse.</li>
          </ul>
        </section>

        <section className="legal-critical">
          <h2>7. Important Financial Disclaimers</h2>

          <h3>7.1 Not Investment, Financial, or Legal Advice</h3>
          <p>
            <strong>BondFactor is not an investment adviser, financial adviser, broker-dealer, financial planner, or fiduciary of any kind.</strong> Nothing in the Service constitutes, or should be interpreted as:
          </p>
          <ul>
            <li>Investment advice or a recommendation regarding any security, loan, asset, or investment strategy.</li>
            <li>A recommendation to buy, sell, hold, or trade any financial instrument.</li>
            <li>An offer or solicitation to buy or sell any security or financial instrument.</li>
            <li>A prediction or forecast of future market performance.</li>
            <li>Tax, legal, or accounting advice.</li>
          </ul>
          <p>
            All outputs, analytics, yield curves, risk assessments, and other Content generated by the Service are provided for <strong>informational and educational purposes only</strong>. They are not designed or intended to direct or influence specific trading or investment activity. You should not rely on any output from the Service as the sole basis for making financial decisions.
          </p>

          <h3>7.2 No Trade Execution</h3>
          <p>
            BondFactor does not execute trades, hold funds, manage assets, or act as a broker-dealer. The Service is purely analytical and educational in nature. Any decision to buy, sell, or hold securities is made solely by you at your own risk and discretion.
          </p>

          <h3>7.3 Market Data</h3>
          <p>
            The Service incorporates market data obtained from publicly available sources, including Financial Benchmarks India Limited (FBIL) and the Reserve Bank of India (RBI). While these sources make reasonable efforts to ensure data accuracy, they make no warranty, representation, or undertaking regarding such data, and expressly disclaim all liability for any errors, omissions, or losses arising from reliance on such data.
          </p>
          <p>
            BondFactor is not affiliated with, endorsed by, or sponsored by FBIL or RBI. All market data is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranty of any kind. You should verify all data against official sources before making any financial decisions.
          </p>

          <h3>7.4 Model-Generated Outputs</h3>
          <p>
            Risk calculations, yield curve models, Nelson-Siegel-Svensson parameters, and all analytical outputs are algorithmically generated and may contain errors, inaccuracies, or omissions. These outputs are estimates only and may not reflect actual market conditions, execution prices, or real-world outcomes. BondFactor does not warrant the accuracy, completeness, or reliability of any model-generated output.
          </p>
          <p>
            All outputs are impersonal, automated, and generated without regard to any user&apos;s portfolio, objectives, financial situation, or risk tolerance.
          </p>

          <h3>7.5 No Advisory or Fiduciary Relationship</h3>
          <p>
            Use of the Service does not create an advisory, fiduciary, broker-customer, professional, or agency relationship between you and BondFactor, its affiliates, officers, employees, or agents.
          </p>

          <h3>7.6 Risk Acknowledgment</h3>
          <p>
            Financial markets involve substantial risk of loss. By using the Service, you acknowledge that you understand these risks and agree to use the Service at your own risk. You accept full responsibility for any and all decisions made based on information obtained through the Service.
          </p>

          <h3>7.7 Past Performance</h3>
          <p>
            Past performance of any security, portfolio, or yield curve model is not indicative of future results. Historical data and back-tested results are presented for informational purposes only and should not be relied upon as predictive of future performance.
          </p>
        </section>

        <section>
          <h2>8. User Content</h2>
          <p>
            You retain ownership of any User Content you input or upload to the Service. By submitting User Content, you grant BondFactor a limited, non-exclusive license to process, store, and use that content solely for the purpose of providing the Service to you.
          </p>
          <p>
            You are solely responsible for the accuracy and legality of your User Content. You shall not upload content that infringes the rights of any third party or violates any applicable law.
          </p>
        </section>

        <section>
          <h2>9. Disclaimer of Warranties</h2>
          <p className="legal-caps">
            THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
          </p>
          <p className="legal-caps">
            WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS. WE MAKE NO WARRANTY REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY CONTENT, INCLUDING ANY ANALYTICAL OUTPUTS, FINANCIAL PROJECTIONS, YIELD CURVE DATA, OR RISK CALCULATIONS.
          </p>
        </section>

        <section>
          <h2>10. Limitation of Liability</h2>
          <p className="legal-caps">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BONDFACTOR, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, REVENUE, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE.
          </p>
          <p className="legal-caps">
            IN NO EVENT SHALL BONDFACTOR BE LIABLE FOR ANY INVESTMENT LOSSES, TRADING LOSSES, OR FINANCIAL DAMAGES ARISING FROM USE OF OR RELIANCE ON ANY INFORMATION, ANALYTICS, YIELD CURVES, RISK CALCULATIONS, OR OTHER OUTPUTS PROVIDED THROUGH THE SERVICE.
          </p>
          <p className="legal-caps">
            OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100 USD).
          </p>
        </section>

        <section>
          <h2>11. Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold harmless BondFactor and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or related to:
          </p>
          <ul>
            <li>Your use of the Service.</li>
            <li>Your violation of these Terms.</li>
            <li>Your violation of any applicable law or regulation.</li>
            <li>Your violation of any third-party rights.</li>
            <li>Your User Content.</li>
          </ul>
        </section>

        <section>
          <h2>12. Termination</h2>
          <p>
            You may terminate your account at any time by contacting us or through your account settings. We may suspend or terminate your access to the Service at any time, with or without cause and with or without notice.
          </p>
          <p>Upon termination:</p>
          <ul>
            <li>Your right to use the Service ceases immediately.</li>
            <li>We may delete your account and data after a reasonable retention period (typically 30 days).</li>
            <li>Provisions of these Terms that by their nature should survive termination will survive, including Sections 5, 7, 9, 10, 11, and 14.</li>
          </ul>
        </section>

        <section>
          <h2>13. Modifications to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page and updating the &quot;Effective Date&quot; above. Your continued use of the Service after any changes constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2>14. Governing Law and Dispute Resolution</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict-of-laws principles. Any dispute arising out of or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the courts of Mumbai, India.
          </p>
        </section>

        <section>
          <h2>15. Severability</h2>
          <p>
            If any provision of these Terms is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.
          </p>
        </section>

        <section>
          <h2>16. Contact Us</h2>
          <p>
            If you have questions about these Terms, please contact us at:
          </p>
          <p className="legal-contact">
            BondFactor<br />
            Email: karbburn@gmail.com<br />
          </p>
        </section>

      </div>
    </div>
  );
}
