"""initial schema

Revision ID: 024dc4274729
Revises: 
Create Date: 2026-07-12 16:43:07.398148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024dc4274729'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curve_calibrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('beta0', sa.Numeric(), nullable=True),
    sa.Column('beta1', sa.Numeric(), nullable=True),
    sa.Column('beta2', sa.Numeric(), nullable=True),
    sa.Column('beta3', sa.Numeric(), nullable=True),
    sa.Column('tau1', sa.Numeric(), nullable=True),
    sa.Column('tau2', sa.Numeric(), nullable=True),
    sa.Column('spline_knots', sa.JSON(), nullable=True),
    sa.Column('optimizer_converged', sa.Boolean(), nullable=False),
    sa.Column('fit_residual_error', sa.Numeric(), nullable=False),
    sa.Column('parameter_stability_delta', sa.Numeric(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('validation_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curve_calibrations_curve_date'), 'curve_calibrations', ['curve_date'], unique=False)
    op.create_table('key_rate_tenor_grid',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('tenor_label', sa.String(), nullable=False),
    sa.Column('tenor_years', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('raw_par_yield_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tenor_label', sa.String(), nullable=True),
    sa.Column('tenor_years', sa.Numeric(), nullable=True),
    sa.Column('par_yield', sa.Numeric(), nullable=True),
    sa.Column('fetch_status', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('parallel_shift', sa.Numeric(), nullable=False),
    sa.Column('slope_shock', sa.Numeric(), nullable=False),
    sa.Column('curvature1_shock', sa.Numeric(), nullable=False),
    sa.Column('curvature2_shock', sa.Numeric(), nullable=False),
    sa.Column('twist_shock', sa.Numeric(), nullable=False),
    sa.Column('twist_pivot', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_scenarios_user_id'), 'saved_scenarios', ['user_id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('security_name', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(), nullable=False),
    sa.Column('coupon_frequency', sa.Numeric(), nullable=False),
    sa.Column('face_value', sa.Numeric(), nullable=False),
    sa.Column('benchmark_tenor_classification', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=True)
    op.create_index(op.f('ix_securities_maturity_date'), 'securities', ['maturity_date'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('face_value_held', sa.Numeric(), nullable=False),
    sa.Column('position_type', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_portfolio_id'), 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_table('reference_zero_curves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('calibration_id', sa.String(length=36), nullable=False),
    sa.Column('tenor_years', sa.Numeric(), nullable=False),
    sa.Column('discount_factor', sa.Numeric(), nullable=False),
    sa.Column('zero_rate', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['curve_calibrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_zero_curves_curve_date'), 'reference_zero_curves', ['curve_date'], unique=False)
    op.create_table('report_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('scenario_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_generations_user_id'), 'report_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_generations_user_id'), table_name='report_generations')
    op.drop_table('report_generations')
    op.drop_index(op.f('ix_reference_zero_curves_curve_date'), table_name='reference_zero_curves')
    op.drop_table('reference_zero_curves')
    op.drop_index(op.f('ix_portfolio_positions_portfolio_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_securities_maturity_date'), table_name='securities')
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_saved_scenarios_user_id'), table_name='saved_scenarios')
    op.drop_table('saved_scenarios')
    op.drop_table('raw_par_yield_observations')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('key_rate_tenor_grid')
    op.drop_index(op.f('ix_curve_calibrations_curve_date'), table_name='curve_calibrations')
    op.drop_table('curve_calibrations')
    # ### end Alembic commands ###
